bug fixes and updates

diff --git a/XU4/initramfs/ramfs/init b/XU4/initramfs/ramfs/init
--- a/XU4/initramfs/ramfs/init
+++ b/XU4/initramfs/ramfs/init
@@ -66,7 +66,11 @@ export fastboot=n
 export forcefsck=n
 export fsckfix=
 export recovery=
-
+export BOOT_CARDTYPE="unknown"
+export OTHER_CARDTYPE="unknown"
+export BOOT_CARDDEV="9"
+export OTHER_CARDDEV="9"
+export CARD_TYPE="SD"
 
 # mdadm needs hostname to be set. This has to be done before the udev rules are called!
 if [ -f "/etc/hostname" ]; then
@@ -88,6 +92,15 @@ DEFAULTBOOT="1"
 # Parse command line options
 for x in $(cat /proc/cmdline); do
     case $x in
+    boot_card_type=*)
+        BOOT_CARDTYPE=${x#boot_card_type=}
+        ;;
+    boot_card_dev=*)
+        BOOT_CARDDEV=${x#boot_card_dev=}
+        ;;
+    cardtype=*)
+        CARD_TYPE=${x#cardtype=}
+        ;;
 	boot_delay=*)
 		BOOTDELAY="${x#boot_delay=}"
 		case ${BOOTDELAY} in
@@ -183,53 +196,18 @@ chown 0:0 /sbin/*
 echo "1 1 1 1" > /proc/sys/kernel/printk
 sleep 1
 
-# ============================
-# === BOOT & TOOLS SELECT  ===
-# ============================
-
-# ========================================================================================
-# During the u-boot (boot.ini):
-# ========================================================================================
-# C2: boots from SDcard if inserted and it is mmc0
-# XU: the BOOT SWITCH SELECTED DRIVE IS ALWAYS mmc0 !!
-# ========================================================================================
-
-# ========================================================================================
-# In initramfs:
-# ========================================================================================
-# When the system has SINGLE CARD inserted, it is always on /dev/mmcblk0
-# ========================================================================================
-# When two cards are inserted (EMMC & SD):
-# ----------------------------------------------------------------------------------------
-# C2: the system ALWAYS BOOTS FROM SDCARD and it is /dev/mmcblk0, EMMC is /dev/mmcblk1
-# ----------------------------------------------------------------------------------------
-# XU: the system boots from EMMC or SDcard depending on BOOT SWITCH, BUT:
-#     EMMC is /dev/mmcblk0 and SDCard is /dev/mmc1 REGARDLESSS OF THE BOOT SWITCH
-# ========================================================================================
-
-# ========================================================================================
-# Mounts:
-# ========================================================================================
-# Single card: on /mnt1
-# ----------------------------------------------------------------------------------------
-# Dual card:
-#   C2: SDCard on /mnt1, EMMC on /mnt2
-#   XU: BOOT CARD on /mnt1, other card on /mnt2
-# ========================================================================================
-
-
 # === Variables ===
 
 [ ! $BOOTDELAY -gt 4 ] &&  BOOTDELAY=5
-export SCRIPT_VERSION="v2.1"
+
+export SCRIPT_VERSION="v2.2"
 export O_BOARD="OD"
 export ODROID_DTB="odroid.dtb"
 export ODROID_FSTAB="fstab.odroid"
 export ODROID_IMAGE="Kernel"
 export ODROID_ASYSTEMIMAGE="androsystem.img"
 export BKP_PREFIX="OD"
-export BOOT_FROM="/dev/mmcblk0"
-export BOOT_CARDTYPE="SD"
+export NUMCARDS="1"
 
 _desc=""
 _ini_prefix="multiboot"
@@ -262,13 +240,13 @@ _mncrd_6="1"
 _mncrd_7="1"
 _mncrd_8="1"
 _boot_delay=2
-_numcards="1"
 _defboot="none"
 _defdescr="none"
 _defcard="1"
 boot_fail="yes"
 
-# === Set come variables depending on used Odroid board ===
+# =========================================================
+# === Set the variables depending on used Odroid board  ===
 if [ -f /ODROID_C2 ]; then
 	O_BOARD="C2"
 	ODROID_DTB="meson64_odroidc2.dtb"
@@ -276,6 +254,13 @@ if [ -f /ODROID_C2 ]; then
 	ODROID_IMAGE="Image"
 	ODROID_ASYSTEMIMAGE="rootsystem.img"
 	BKP_PREFIX="C2"
+	BOOT_CARDTYPE="SD"
+	BOOT_CARDDEV="0"
+	if [ -b /dev/mmcblk1p1 ]; then
+		NUMCARDS="2"
+		OTHER_CARDDEV="1"
+		OTHER_CARDTYPE="EMMC"
+	fi
 elif [ -f /ODROID_XU ]; then
 	O_BOARD="XU"
 	ODROID_DTB="exynos5422-odroidxu3.dtb"
@@ -283,8 +268,33 @@ elif [ -f /ODROID_XU ]; then
 	ODROID_IMAGE="zImage"
 	ODROID_ASYSTEMIMAGE="system.img"
 	BKP_PREFIX="XU"
-fi
 
+	if [ "${BOOT_CARDTYPE}" = "none" ]; then
+		BOOT_CARDTYPE="SD"
+		if [ -b /dev/mmcblk1p1 ]; then
+			NUMCARDS="2"
+			BOOT_CARDDEV="1"
+			OTHER_CARDDEV="0"
+			OTHER_CARDTYPE="EMMC"
+		else
+			BOOT_CARDDEV="0"
+		fi
+	else
+		[ "${BOOT_CARDTYPE}" = "eMMC" ] && BOOT_CARDTYPE="EMMC"
+		if [ "${BOOT_CARDDEV}" = 1 ]; then
+			NUMCARDS="2"
+			if [ "${BOOT_CARDTYPE}" = "SD" ]; then
+				OTHER_CARDDEV="0"
+				OTHER_CARDTYPE="EMMC"
+			else
+				OTHER_CARDDEV="1"
+				OTHER_CARDTYPE="SD"
+				BOOT_CARDDEV="0"
+			fi
+		fi
+	fi
+fi
+# =========================================================
 
 # === Functions ===
 
@@ -304,6 +314,52 @@ get_descr() {
 #-----------------------------------------------------
 
 
+#-----------------------------------------------------------------------------------------------------------------------
+change_afstab() {
+	# === Configure Android fstab to mount the right partitions ===
+	if [ -f /mnt_a/${ODROID_FSTAB}${1} ]; then
+		if [ "${2}" = "yes" ]; then
+			# Two cards, boot to Android on NON Boot card
+			if [ "${O_BOARD}" = "C2" ]; then
+				cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
+			else
+				if [ "${OTHER_CARDTYPE}" = "SD" ]; then
+					cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
+				else
+					cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
+				fi
+			fi
+		else
+			if [ "${O_BOARD}" = "C2" ]; then
+				cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
+			else
+				if [ "${NUMCARDS}" = "1" ]; then
+					cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
+				else
+					# Two cards, boot to Android on Boot card
+					if [ "${BOOT_CARDTYPE}" = "SD" ]; then
+						cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
+					else
+						cat /mnt_a/${ODROID_FSTAB}${1} | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
+					fi
+				fi
+			fi
+		fi
+		cp _fstab_ /mnt_a/${ODROID_FSTAB}${1} > /dev/null 2>&1
+		rm _fstab_ > /dev/null 2>&1
+	elif [ "${1}" = "" ]; then
+		printf "\033[31m\033[1m %s not found\033[22m\033[37m" "${ODROID_FSTAB}${1}"
+		cp /mnt1/${_ini_prefix}/boot.ini.multi /mnt1/boot.ini > /dev/null 2>&1
+		[ "${O_BOARD}" = "XU" ] && cp /mnt1/${_ini_prefix}/boot.scr.multi /mnt1/boot.scr > /dev/null 2>&1
+		sleep 3
+		umount /mnt_a > /dev/null 2>&1
+		return 1
+	fi
+	return 0
+}
+#-----------------------------------------------------------------------------------------------------------------------
+
+
 #----------------------------------------------------------------------------------------------------------------------
 # =======================================================================
 # On C2 boot drive is always mmcblk0 and is mounted on /mnt1
@@ -314,26 +370,17 @@ do_boot() {
 
 	local change_drive="no"
 	local _oncard=""
-
 	_actmount="mnt1"
 	if [ "${3}" = "2" ]; then
 		_actmount="mnt2"
 		change_drive="yes"
 	fi
 
-	if [ "${_numcards}" = "2" ]; then
-		if [ "${O_BOARD}" = "C2" ]; then
-			if [ "${_actmount}" = "mnt1" ]; then
-				_oncard=" on EMMC"
-			else
-				_oncard=" on SDcard"
-			fi
+	if [ "${NUMCARDS}" = "2" ]; then
+		if [ "${_actmount}" = "mnt1" ]; then
+			_oncard=" on ${BOOT_CARDTYPE}"
 		else
-			if [ "${_actmount}" = "mnt1" ] && [ "${BOOT_FROM}" = "/dev/mmcblk1" ]; then
-				_oncard=" on SDcard"
-			else
-				_oncard=" on EMMC"
-			fi
+			_oncard=" on ${OTHER_CARDTYPE}"
 		fi
 	fi
 
@@ -342,7 +389,7 @@ do_boot() {
 		printf "\r\033[2K"
 		printf "    Booting to \033[32m%s\033[37m\033[36m%s\033[37m" "${2}" "${_oncard}"
 
-		# === Copy selected boot.ini fo BOOT partition
+		# === Copy selected boot.ini to BOOT partition
 		cp /${_actmount}/${_ini_prefix}/${1} /mnt1/boot.ini > /dev/null 2>&1
 		if [ ! $? -eq 0 ]; then
 			cp /mnt1/${_ini_prefix}/boot.ini.multi /mnt1/boot.ini > /dev/null 2>&1
@@ -354,32 +401,31 @@ do_boot() {
 		sleep 1
 
 		if [ "${change_drive}" = "yes" ]; then
-			# === boot.ini from SDcard, prepare for boot from mmc 1:1 ===
-			# for kernel/initrd/dtb loading
-			cat /mnt1/boot.ini | sed "s/0:1/1:1/g" > _bini_
-			cp _bini_ /mnt1/boot.ini
-			rm _bini_
-			# for boot.ini loading from /multiboot (it was changed with previous sed operation!)
-			cat /mnt1/boot.ini | sed "s/1:1 0x60000000/0:1 0x60000000/g" > _bini_
-			cp _bini_ /mnt1/boot.ini
-			rm _bini_
+			# === boot.ini from NON-BOOT card, prepare for boot from BOOT card ===
+			if [ "${O_BOARD}" = "C2" ]; then
+				# for kernel/initrd/dtb loading
+				cat /mnt1/boot.ini | sed "s/fatload mmc 0:1/fatload mmc 1:1/g" > _bini_
+				cp _bini_ /mnt1/boot.ini
+				rm _bini_
+				# for boot.ini loading from /multiboot (it was changed with previous sed operation!)
+				cat /mnt1/boot.ini | sed "s/1:1 0x60000000/0:1 0x60000000/g" > _bini_
+				cp _bini_ /mnt1/boot.ini
+				rm _bini_
+			else
+				# for kernel/initrd/dtb loading
+				cat /mnt1/boot.ini | sed "s/setenv change_osdev no/setenv change_osdev yes/g" > _bini_
+				cp _bini_ /mnt1/boot.ini
+				rm _bini_
+			fi
 		fi
 
 		if [ "${1}" = "boot.ini.android" ]; then
 			# === mount android system partition to prepare android fstab ===
 			mkdir /mnt_a > /dev/null 2>&1
 			if [ "${change_drive}" = "yes" ]; then
-				if [ "${BOOT_FROM}" = "/dev/mmcblk0" ]; then
-					mount -t ext4 /dev/mmcblk1p2 /mnt_a > /dev/null 2>&1
-				else
-					mount -t ext4 /dev/mmcblk0p2 /mnt_a > /dev/null 2>&1
-				fi
+				mount -t ext4 /dev/mmcblk${OTHER_CARDDEV}p2 /mnt_a > /dev/null 2>&1
 			else
-				if [ "${BOOT_FROM}" = "/dev/mmcblk0" ]; then
-					mount -t ext4 /dev/mmcblk0p2 /mnt_a > /dev/null 2>&1
-				else
-					mount -t ext4 /dev/mmcblk1p2 /mnt_a > /dev/null 2>&1
-				fi
+				mount -t ext4 /dev/mmcblk${BOOT_CARDDEV}p2 /mnt_a > /dev/null 2>&1
 			fi
 			if [ $? -ne 0 ]; then
 				printf "\033[31m\033[1m Mount Android system partition ERROR\033[22m\033[37m"
@@ -391,51 +437,23 @@ do_boot() {
 			fi
 
 			# === Configure Android fstab to mount the right partitions ===
-			if [ -f /mnt_a/${ODROID_FSTAB} ]; then
-				if [ "${change_drive}" = "yes" ]; then
-					cat /mnt_a/${ODROID_FSTAB} | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
-				else
-					cat /mnt_a/${ODROID_FSTAB} | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
-				fi
-				cp _fstab_ /mnt_a/${ODROID_FSTAB}
-				rm _fstab_
-			else
-				printf "\033[31m\033[1m %s not found\033[22m\033[37m" "${ODROID_FSTAB}"
-				cp /mnt1/${_ini_prefix}/boot.ini.multi /mnt1/boot.ini > /dev/null 2>&1
-				[ "${O_BOARD}" = "XU" ] && cp /mnt1/${_ini_prefix}/boot.scr.multi /mnt1/boot.scr > /dev/null 2>&1
-				sleep 3
-				umount /mnt_a > /dev/null 2>&1
-				return 1
-			fi
-			if [ -f /mnt_a/${ODROID_FSTAB}.sdcard ]; then
-				if [ "${change_drive}" = "yes" ]; then
-					cat /mnt_a/${ODROID_FSTAB}.sdcard | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
-				else
-					cat /mnt_a/${ODROID_FSTAB}.sdcard | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
-				fi
-				cp _fstab_ /mnt_a/${ODROID_FSTAB}.sdcard
-				rm _fstab_
-			fi
-			if [ -f /mnt_a/${ODROID_FSTAB}.sdboot ]; then
-				if [ "${change_drive}" = "yes" ]; then
-					cat /mnt_a/${ODROID_FSTAB}.sdboot | sed "s/\/dev\/block\/mmcblk0/\/dev\/block\/mmcblk1/g" > _fstab_
-				else
-					cat /mnt_a/${ODROID_FSTAB}.sdboot | sed "s/\/dev\/block\/mmcblk1/\/dev\/block\/mmcblk0/g" > _fstab_
-				fi
-				cp _fstab_ /mnt_a/${ODROID_FSTAB}.sdboot
-				rm _fstab_
-			fi
+			change_afstab "" "${change_drive}"
+			[ $? -ne 0 ] && return 1
+			change_afstab ".sdcard" "${change_drive}"
+			change_afstab ".sdboot" "${change_drive}"
+			umount /mnt_a > /dev/null 2>&1
+			# =============================================================
 
-			if [ "${change_drive}" = "yes" ]; then
-				# prepare boot.ini for boot from sdcard
+			if [ "${O_BOARD}" = "C2" ] && [ "${change_drive}" = "yes" ]; then
+				# on C2 prepare boot.ini for boot from sdcard, not needed on XU
 				cat /mnt1/boot.ini | sed "s/root=\/dev\/mmcblk0p2/root=\/dev\/mmcblk1p2/g" > _bini_
 				cp _bini_ /mnt1/boot.ini
 				rm _bini_
 			fi
-			umount /mnt_a > /dev/null 2>&1
 		fi
 
 		if [ "${O_BOARD}" = "XU" ]; then
+			# Convert boot.ini to boot.scr
 			mkimage -C none -A arm -T script -d /mnt1/boot.ini /mnt1/boot.scr > /dev/null 2>&1
 			if [ $? -ne 0 ]; then
 				printf "\033[31m\033[1m mkimage (boot.scr) ERROR\033[22m\033[37m"
@@ -501,19 +519,11 @@ set_menu_key() {
 # shellcheck disable=SC2059
 get_menu_items() {
 	local _oncard=""
-	if [ "${_numcards}" = "2" ]; then
-		if [ "${O_BOARD}" = "C2" ]; then
-			if [ "${_actmount}" = "mnt1" ]; then
-				_oncard=" on EMMC"
-			else
-				_oncard=" on SDcard"
-			fi
+	if [ "${NUMCARDS}" = "2" ]; then
+		if [ "${_actmount}" = "mnt1" ]; then
+			_oncard=" on ${BOOT_CARDTYPE}"
 		else
-			if [ "${_actmount}" = "mnt1" ] && [ "${BOOT_FROM}" = "/dev/mmcblk1" ]; then
-				_oncard=" on SDcard"
-			else
-				_oncard=" on EMMC"
-			fi
+			_oncard=" on ${OTHER_CARDTYPE}"
 		fi
 	fi
 	if [ -f /${_actmount}/${_ini_prefix}/boot.ini.android ]; then
@@ -595,7 +605,6 @@ os_detect() {
 	_mncrd_7="1"
 	_mncrd_8="1"
 	_boot_delay=2
-	_numcards="1"
 	_defboot="none"
 	_defdescr="none"
 	_defcard="1"
@@ -608,82 +617,23 @@ os_detect() {
 	umount /mnt > /dev/null 2>&1
 
 	clear
+	# Detect new partitions after install
 	blkid  > /dev/null 2>&1
 
-	printf "\n\n    Detecting cards...\n"
-
-	# === Detect mmc cards ===
-	_numcards="0"
-	BOOT_FROM="none"
 	# ================================
-	# Find boot card, mount both cards
+	# Mount available cards
 	# ================================
-	mount -t vfat /dev/mmcblk0p1 /mnt1 > /dev/null 2>&1
+	mount -t vfat /dev/mmcblk${BOOT_CARDDEV}p1 /mnt1 > /dev/null 2>&1
 	if [ $? -eq 0 ]; then
-		_numcards="1"
-		if [ -f /mnt1/_BOOT_FROM_ ]; then
-			# BOOT DRIVE IS mmcblk0
-			BOOT_FROM="/dev/mmcblk0"
-			rm -f /mnt1/_BOOT_FROM_ > /dev/null 2>&1
-		fi
-		# === Check if the 2nd card is present ===
-		if [ -b /dev/mmcblk1p1 ]; then
-			mount -t vfat /dev/mmcblk1p1 /mnt2 > /dev/null 2>&1
-			if [ $? -eq 0 ]; then
-				_numcards="2"
-				if [ "${O_BOARD}" = "XU" ]; then
-					# On XU3/XU4 the boot card can be SDcard or EMMC
-					if [ -f /mnt2/_BOOT_FROM_ ]; then
-						# === BOOT FROM SDcard ===
-						rm -f /mnt2/_BOOT_FROM_ > /dev/null 2>&1
-						if [ "${BOOT_FROM}" = "none" ]; then
-							# === remount boot drive to /mnt1 ===
-							umount /mnt1 > /dev/null 2>&1
-							umount /mnt2 > /dev/null 2>&1
-							sleep 1
-							mount -t vfat /dev/mmcblk1p1 /mnt1 > /dev/null 2>&1
-							mount -t vfat /dev/mmcblk0p1 /mnt2 > /dev/null 2>&1
-							BOOT_FROM="/dev/mmcblk1"
-						fi
-					fi
-				else
-					rm -f /mnt2/_BOOT_FROM_ > /dev/null 2>&1
-					BOOT_FROM="/dev/mmcblk0"
-				fi
+		if [ "${NUMCARDS}" = "2" ]; then
+			mount -t vfat /dev/mmcblk${OTHER_CARDDEV}p1 /mnt2 > /dev/null 2>&1
+			if [ $? -ne 0 ]; then
+				OTHER_CARDDEV="9"
 			fi
-		else
-			BOOT_FROM="/dev/mmcblk0"
 		fi
 	else
 		# === SOMETHING IS VERY WRONG ===
 		do_halt "BOOT CARD NOT MOUNTABLE"
-	fi
-
-	if [ "${O_BOARD}" = "XU" ]; then
-		[ -b /dev/mmcblk0boot0 ] && BOOT_CARDTYPE="EMMC"
-	fi
-
-	if [ "${BOOT_FROM}" = "none" ]; then
-		printf "\033[31m\033[1m    WARNING:\033[36m\n"
-		printf "    ==========================================================\n"
-		printf "    = Two cards detected, the boot card cannot be determined =\n"
-		printf "    = You have probably booted from original Odroid card     =\n"
-		printf "    ==========================================================\n\n"
-		printf "    Have you booted from SD Card ? (y/N) "
-		BOOT_FROM="/dev/mmcblk0"
-		B="X"
-		_delay=60
-		while [ $_reboot_delay -gt 0 ]; do
-			if read -n 1 -t 1 -s B; then
-				_delay=60
-				if [ "${B}" = "y" ] || [ "${B}" = "Y" ]; then
-					BOOT_FROM="/dev/mmcblk1"
-					break
-				fi
-			else
-				let _delay=_delay-1
-			fi
-		done
 	fi
 
 	clear
@@ -698,7 +648,12 @@ os_detect() {
 		printf "    = ODROID XU3/XU4 BOOT MENU %s =\n" "${SCRIPT_VERSION}"
 		printf "    =================================\n"
 	fi
-	printf "\033[22m\033[37m\n"
+	if [ "${NUMCARDS}" = "2" ]; then
+		printf "\033[22m    Two cards detected, booted from \033[1m%s\033[22m\033[37m\n\n" "${BOOT_CARDTYPE}"
+	else
+		printf "\033[22m    Booted from \033[1m%s\033[22m\033[37m\n\n" "${BOOT_CARDTYPE}"
+	fi
+
 
 	#===================================================
 	# === Detect available OS's and print menu items ===
@@ -708,7 +663,7 @@ os_detect() {
 	_actmount="mnt1"
 	if [ -b /dev/disk/by-label/sduserdata ] || [ -b /dev/disk/by-label/emuserdata ]; then
 		get_menu_items
-		if [ "${_numcards}" = "2" ]; then
+		if [ "${NUMCARDS}" = "2" ]; then
 			_actmount="mnt2"
 			[ ! ${_numos} -eq 0 ] && printf "\n"
 			get_menu_items
@@ -915,7 +870,7 @@ while true; do
 		elif [ "${A}" = "s" ]; then
 			# SCREENSHOT ===
 			fbcat > /mb_menu.ppm
-		elif [ ! "${BOOT_FROM}" = "none" ]; then
+		elif [ $_numos -gt 0 ]; then
 			# === BOOT to selected OS
 			boot_fail="no"
 			[ "${A}" = "1" ] && [ ! "${_menuitem_1}" = "none" ] && do_boot "${_menuitem_1}" "${_mndscr_1}" "${_mncrd_1}"
